version: '3.7'
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto-config:/mosquitto/:rw
    ports:
      - "1883:1883"
      - "9001:9001"
    environment:
      - TZ=Europe/Oslo
    networks:
      - zwave

  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=mysupersecretkey
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      # Uncomment if you want logs time and dates to match your timezone instead of UTC
      # Available at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=Europe/Oslo
    networks:
      - zwave
    devices:
      # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
      # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
      #      - '/dev/ttyAMA0:/dev/zwave'
      - '/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave'
    volumes:
      - ./zwave-config:/usr/src/app/store
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for Z-Wave JS websocket server

  domoticz:
    image: domoticz/domoticz
    container_name: domoticz
    restart: unless-stopped

    ports:
      - "8080:8080"
    volumes:
      - ./domoticz-config:/opt/domoticz/userdata
    environment:
      - TZ=Europe/Oslo
      - LOG_PATH=/opt/domoticz/userdata/domoticz.log
    networks:
      - zwave


networks:
  zwave:
volumes:
  zwave-config:
    name: zwave-config
